#!/bin/sh
#PBS -l nodes=1:ppn=4

########### UPDATE THESE VARIABLES ###############
# the directory where your files are
pa4_home=/home/$USER/pa4/
##################################################

cd $pa4_home
echo $USER
echo $pa4_home
######### ADD YOUR EXECUTION SCRIPT HERE #########
# Set the number of threads
export OMP_NUM_THREADS=4
# Clean up the directory
make clean
# Compile the program
make
# Run Mergesort
./mergesort 100000 3000000 48000000 1
# Run radixsort
./radixsort 1000000
